# Generated by Django 5.1.3 on 2025-02-23 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstapp", "0003_chatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="subscriber",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_messages",
                to="firstapp.subscriber",
            ),
            preserve_default=False,
        ),
    ]
